<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Final Analysis – Operation Lone Star Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6bd9cfa162949bde0a231f530c97869d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Operation Lone Star Project</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Project Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./01-cleaning-versa.html"> 
<span class="menu-text">Maria’s Cleaning</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./01-spurs-cleaning.html"> 
<span class="menu-text">Olivia’s Cleaning</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./02-combine.html"> 
<span class="menu-text">Combining the Datasets</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./03-olivia-analysis.html"> 
<span class="menu-text">Olivia’s Analysis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./04-analysisgraphics.html" aria-current="page"> 
<span class="menu-text">Final Analysis</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#goals-of-this-notebook" id="toc-goals-of-this-notebook" class="nav-link active" data-scroll-target="#goals-of-this-notebook">Goals of this notebook</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#importing-cleaned-data" id="toc-importing-cleaned-data" class="nav-link" data-scroll-target="#importing-cleaned-data">Importing cleaned data</a></li>
  <li><a href="#categorizing-charges" id="toc-categorizing-charges" class="nav-link" data-scroll-target="#categorizing-charges">Categorizing charges</a>
  <ul class="collapse">
  <li><a href="#creating-categories" id="toc-creating-categories" class="nav-link" data-scroll-target="#creating-categories">Creating categories</a></li>
  </ul></li>
  <li><a href="#demographics" id="toc-demographics" class="nav-link" data-scroll-target="#demographics">Demographics</a>
  <ul class="collapse">
  <li><a href="#who-is-being-arrested" id="toc-who-is-being-arrested" class="nav-link" data-scroll-target="#who-is-being-arrested">Who is being arrested?</a></li>
  <li><a href="#breaking-down-offenders-charges-by-races" id="toc-breaking-down-offenders-charges-by-races" class="nav-link" data-scroll-target="#breaking-down-offenders-charges-by-races">Breaking down offenders’ charges by races</a></li>
  <li><a href="#now-well-look-at-who-is-doing-the-arresting-and-where" id="toc-now-well-look-at-who-is-doing-the-arresting-and-where" class="nav-link" data-scroll-target="#now-well-look-at-who-is-doing-the-arresting-and-where">Now we’ll look at who is doing the arresting and where?</a></li>
  </ul></li>
  <li><a href="#categories" id="toc-categories" class="nav-link" data-scroll-target="#categories">Categories</a>
  <ul class="collapse">
  <li><a href="#drug" id="toc-drug" class="nav-link" data-scroll-target="#drug">Drug</a></li>
  <li><a href="#solo-drug-charges" id="toc-solo-drug-charges" class="nav-link" data-scroll-target="#solo-drug-charges">Solo Drug Charges</a></li>
  <li><a href="#smuggling" id="toc-smuggling" class="nav-link" data-scroll-target="#smuggling">Smuggling</a></li>
  </ul></li>
  <li><a href="#smuggling-by-county-and-race" id="toc-smuggling-by-county-and-race" class="nav-link" data-scroll-target="#smuggling-by-county-and-race">Smuggling by county and race</a></li>
  <li><a href="#breaking-down-the-black-smuggling-category-by-county-to-test-laurens-theory" id="toc-breaking-down-the-black-smuggling-category-by-county-to-test-laurens-theory" class="nav-link" data-scroll-target="#breaking-down-the-black-smuggling-category-by-county-to-test-laurens-theory">Breaking down the Black smuggling category by county to test Lauren’s theory</a>
  <ul class="collapse">
  <li><a href="#now-lets-see-the-breakdowns-for-other-races-starting-with-white-smuggling-arrests." id="toc-now-lets-see-the-breakdowns-for-other-races-starting-with-white-smuggling-arrests." class="nav-link" data-scroll-target="#now-lets-see-the-breakdowns-for-other-races-starting-with-white-smuggling-arrests.">Now let’s see the breakdowns for other races, starting with white smuggling arrests.</a></li>
  <li><a href="#now-lets-see-the-hispanic-breakdown." id="toc-now-lets-see-the-hispanic-breakdown." class="nav-link" data-scroll-target="#now-lets-see-the-hispanic-breakdown.">Now let’s see the Hispanic breakdown.</a></li>
  <li><a href="#kinney" id="toc-kinney" class="nav-link" data-scroll-target="#kinney">Kinney</a></li>
  </ul></li>
  <li><a href="#lets-compare-percentages-of-arrests-by-races-with-tabyls" id="toc-lets-compare-percentages-of-arrests-by-races-with-tabyls" class="nav-link" data-scroll-target="#lets-compare-percentages-of-arrests-by-races-with-tabyls">Let’s compare percentages of arrests by races with tabyls</a>
  <ul class="collapse">
  <li><a href="#county-and-race-tabyl" id="toc-county-and-race-tabyl" class="nav-link" data-scroll-target="#county-and-race-tabyl">County and race tabyl</a></li>
  <li><a href="#smuggling-arrests-by-race-and-county" id="toc-smuggling-arrests-by-race-and-county" class="nav-link" data-scroll-target="#smuggling-arrests-by-race-and-county">Smuggling arrests by race and county %</a></li>
  <li><a href="#looking-into-specific-officers" id="toc-looking-into-specific-officers" class="nav-link" data-scroll-target="#looking-into-specific-officers">Looking into specific officers</a></li>
  </ul></li>
  <li><a href="#main-takeaways" id="toc-main-takeaways" class="nav-link" data-scroll-target="#main-takeaways">Main takeaways</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Final Analysis</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="goals-of-this-notebook" class="level2">
<h2 class="anchored" data-anchor-id="goals-of-this-notebook">Goals of this notebook</h2>
<p>The purpose of this notebook is to combine Maria and Olivia’s analyses into one easily digestible notebook. For a closer look at what each of us did, you can look at our individual cleaning notebooks.</p>
<p>We worked together to answer these questions:</p>
<ul>
<li>Who is being arrested?</li>
<li>Who is doing the arresting?</li>
<li>What kinds of crimes are being committed?</li>
<li>How many are drug crimes?</li>
<li>What kind of drugs? Is it fentanyl like Abbott says?</li>
</ul>
<p>Let’s get into it.</p>
</section>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<p>We’ll load our libraries.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="importing-cleaned-data" class="level2">
<h2 class="anchored" data-anchor-id="importing-cleaned-data">Importing cleaned data</h2>
<p>Then we’ll import our cleaned data from our combined data sets.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>olsdata <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data-processed/02-combine.rds"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>olsdata</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 58,635 × 25
   primary_key charge              charge_count ethnicity charge_date person_age
   &lt;chr&gt;       &lt;chr&gt;                      &lt;dbl&gt; &lt;chr&gt;     &lt;date&gt;           &lt;dbl&gt;
 1 TX20234     Poss Marij &lt; 2OZ               1 H         2023-01-03          27
 2 TX20234     Poss CS PG 2 &gt;= 1G…            1 H         2023-01-03          27
 3 TX20235     WARRANT: ASSAULTIV…            1 H         2023-01-21          50
 4 TX20237     Criminal Trespass              1 H         2023-01-22          37
 5 TX20238     Criminal Trespass              1 H         2023-01-22          NA
 6 TX20239     Criminal Trespass              1 H         2023-01-22          26
 7 TX202310    Criminal Trespass              1 H         2023-01-22          21
 8 TX202311    Criminal Trespass              1 H         2023-01-22          NA
 9 TX202312    Criminal Trespass              1 H         2023-01-22          29
10 TX202313    Criminal Trespass              1 H         2023-01-22          NA
# ℹ 58,625 more rows
# ℹ 19 more variables: person_first_name &lt;chr&gt;, person_second_name &lt;chr&gt;,
#   person_third_name &lt;chr&gt;, person_last_name &lt;chr&gt;, officer_id &lt;dbl&gt;,
#   arrest_county &lt;chr&gt;, code &lt;chr&gt;, severity_code &lt;chr&gt;,
#   severity_code_clean &lt;chr&gt;, person_race_abbr &lt;chr&gt;,
#   person_gender_abbr &lt;chr&gt;, arrest_state &lt;chr&gt;, arrest_division &lt;chr&gt;,
#   arrest_id &lt;dbl&gt;, arrest_urn &lt;chr&gt;, arresting_officer &lt;chr&gt;, …</code></pre>
</div>
</div>
</section>
<section id="categorizing-charges" class="level2">
<h2 class="anchored" data-anchor-id="categorizing-charges">Categorizing charges</h2>
<p>The first thing we want to do is create categories for these charges. We won’t use them immediately to answer our demographics questions, but it will come in handy later when we look into each race and the charge breakdowns within them. We’ll also use them later to break down specific charge categories, like smuggling and drug arrests.</p>
<p>Within Operation Lone Star, there are 490 different types of charges. Therefore, we decided to break down the charges into 11 different categories. Here’s a key that describes each category.</p>
<p>Operation Lone Star Charge Category Key:</p>
<ul>
<li><strong>Drug</strong> = Any charge that relates to possession or manufacturing of drug, as well as any drug-related charges like stash house charges. Something to note is that some charges are both “drug/weapon” offenses.</li>
<li><strong>Weapon</strong> = Any charge relating to possession/use of unauthorized firearms or weapons.</li>
<li><strong>Warrant/Conspiracy</strong> = General charges.</li>
<li><strong>Smuggling/Trafficking of Persons</strong> = Human trafficking or smuggling charges. This category also includes charges for smuggling both persons and firearms.</li>
<li><strong>Trespassing</strong> = Includes all types of trespassing charges.</li>
<li><strong>Immigration Other</strong> = Immigration related charges.</li>
<li><strong>Evasion/Fleeing</strong> = Escaping authority charges.</li>
<li><strong>Organized Crime</strong></li>
<li><strong>Tampering</strong> = Charges related to tampering with evidence.</li>
<li><strong>Unauthorized Use of Vehicle</strong></li>
<li><strong>Money Laundering</strong></li>
</ul>
<section id="creating-categories" class="level3">
<h3 class="anchored" data-anchor-id="creating-categories">Creating categories</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>cat_ols <span class="ot">&lt;-</span> olsdata <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">charge_cat =</span> <span class="fu">case_when</span>(</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>        charge,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Drug|CS|Cs|Mari|DRUG|MARI|Marj|MARJ|Man|Subs|Stash|Chem"</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>      ) <span class="sc">~</span> <span class="st">"Drug"</span>,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>        charge,</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Smugg|SMUGG|Trafficking|TRAFFICKING|Trans|Bringing In"</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>      ) <span class="sc">~</span> <span class="st">"Smuggling/Trafficking of Persons"</span>,</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(charge, <span class="st">"Firearm|FIREARM|gun|GUN|Amm|Arm|Weapon|WEAPON"</span>) <span class="sc">~</span> <span class="st">"Weapon"</span>,</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(charge, <span class="st">"Launder|LAUNDER"</span>) <span class="sc">~</span> <span class="st">"Money Laundering"</span>,</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(charge, <span class="st">"Trespass|TRESPASS"</span>) <span class="sc">~</span> <span class="st">"Trespassing"</span>,</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(charge, <span class="st">"Alien|ALIEN|Visa|VISA|IMMIGRATION|Immigration"</span>) <span class="sc">~</span> <span class="st">"Immigration Other"</span>,</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(charge, <span class="st">"Evad|EVAD|Flee|FLEE"</span>) <span class="sc">~</span> <span class="st">"Evasion/Fleeing"</span>,</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(charge, <span class="st">"Organized|Enterprise"</span>) <span class="sc">~</span> <span class="st">"Organized Crime"</span>,</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(charge, <span class="st">"Tamp|TAMP"</span>) <span class="sc">~</span> <span class="st">"Tampering"</span>,</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(charge, <span class="st">"Unauth"</span>) <span class="sc">~</span> <span class="st">"Unauthorized Use of Vehicle"</span>,</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(charge, <span class="st">"Warrant|WARRANT"</span>) <span class="sc">~</span> <span class="st">"Warrant"</span>,</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(charge, <span class="st">"Conspiracy|CONSPIRACY"</span>) <span class="sc">~</span> <span class="st">"Conspiracy"</span></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>    ,</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">.default =</span> <span class="st">"Other"</span></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>cat_ols <span class="sc">|&gt;</span></span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(charge_cat, charge)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 490 × 3
   charge_cat charge                                                           n
   &lt;chr&gt;      &lt;chr&gt;                                                        &lt;int&gt;
 1 Conspiracy Attempt And Conspiracy                                           7
 2 Conspiracy Attempt And Conspiracy (21 Usc Sec 963)                          1
 3 Conspiracy Attempt And Conspiracy (Other Title 21 Violations)               4
 4 Conspiracy Conspiracy (General/Other Title 21)                             10
 5 Drug       (FENTANYL) POSS CS PG 1 &lt;1G                                      1
 6 Drug       (HEROIN) POSS CS PG 1 &lt;1G                                        1
 7 Drug       Conspiracy To Possess With Intent To Distribute Controlled …   201
 8 Drug       Conspiracy To Sale/Manfct/Dist Controlled Substance            122
 9 Drug       Controlled Substance Offenses-Felony                           110
10 Drug       Controlled Substance Offenses-Misdemeanor                       11
# ℹ 480 more rows</code></pre>
</div>
</div>
<p>Then we’ll do a quick group_by, summarize, arrange to see the categories and allow us to visualize it in a second.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>cat_chart <span class="ot">&lt;-</span> cat_ols <span class="sc">|&gt;</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(charge_cat) <span class="sc">|&gt;</span> </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">charge_num =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span> </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(charge_num))</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>cat_chart</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13 × 2
   charge_cat                       charge_num
   &lt;chr&gt;                                 &lt;int&gt;
 1 Drug                                  23233
 2 Trespassing                           11439
 3 Smuggling/Trafficking of Persons      10965
 4 Evasion/Fleeing                        4619
 5 Warrant                                4158
 6 Weapon                                 1967
 7 Unauthorized Use of Vehicle             853
 8 Tampering                               698
 9 Organized Crime                         342
10 Money Laundering                        182
11 Immigration Other                       152
12 Conspiracy                               22
13 Other                                     5</code></pre>
</div>
</div>
<p>Now that we’ve got that, let’s make a chart to visualize it. We’ll use ggplot, pull cat_chart back up, and create a simple bar chart. We reordered the bars so that the category is on the y axis so the readability is better. Then we adjusted the number labels so you can read them better and gave the bars a color. Now we can see which categories are the most prolific.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(cat_chart, <span class="fu">aes</span>(<span class="at">x =</span> charge_num, <span class="at">y =</span> <span class="fu">reorder</span>(charge_cat, charge_num))) <span class="sc">+</span>     </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"#0AB7F7"</span>) <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> charge_num, <span class="at">hjust =</span> <span class="fu">ifelse</span>(charge_num <span class="sc">&gt;</span> <span class="dv">1967</span>, <span class="fl">1.1</span>, <span class="sc">-</span>.<span class="dv">1</span>)),</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">title =</span> <span class="st">"What is Operation Lone Star Actually Doing?"</span>,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">x =</span> <span class="st">"Number of Charges"</span>,</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">y =</span> <span class="st">"Charge Category"</span>,</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">subtitle =</span> <span class="fu">str_wrap</span>(<span class="st">"This chart looks at the different types of charges  under Operation Lone Star. Notably, the most popular type of charge is drug-related."</span>),</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Source = Operation Lone Star Data"</span>,</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>      )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-analysisgraphics_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From this simple chart, we can see a couple preliminary takeaways:</p>
<ul>
<li>At least 23,233 charges under Operation Lone Star are drug-related.</li>
<li>Categories like money laundering, tampering with evidence and unauthorized use of vehicle are more common than immigration related charges.</li>
</ul>
<p>Now that we have that for later, we’ll get into the demographics data.</p>
</section>
</section>
<section id="demographics" class="level2">
<h2 class="anchored" data-anchor-id="demographics">Demographics</h2>
<p>The first set of questions we want to answer look at demographics - who is being arrested under OLS and who is doing that arresting.</p>
<section id="who-is-being-arrested" class="level3">
<h3 class="anchored" data-anchor-id="who-is-being-arrested">Who is being arrested?</h3>
<p>Let’s look at sex, ethnicity, age, and race.</p>
<section id="sex" class="level4">
<h4 class="anchored" data-anchor-id="sex">Sex:</h4>
<p>We call our data, group by the arrested person’s sex, then summarize and arrange that so we can see it in descending order. We’ll put that into a bucket so we can refer to it later in our visual component.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>olsgender <span class="ot">&lt;-</span> olsdata <span class="sc">|&gt;</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(person_gender_abbr) <span class="sc">|&gt;</span> </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">appearances =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span> </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(appearances))</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>olsgender</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  person_gender_abbr appearances
  &lt;chr&gt;                    &lt;int&gt;
1 M                        48297
2 F                        10147
3 &lt;NA&gt;                       180
4 U                           11</code></pre>
</div>
</div>
<p>We can see that there’s an overwhelming majority of males being arrested under Operation Lone Star.</p>
<section id="creating-a-graph-for-sex-demographics" class="level5">
<h5 class="anchored" data-anchor-id="creating-a-graph-for-sex-demographics">Creating a graph for sex demographics</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(olsgender, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(person_gender_abbr, appearances), <span class="at">y =</span> appearances)) <span class="sc">+</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Operation Lone Star arrests by sex"</span>,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="fu">str_wrap</span>(<span class="st">"Operation Lone Star is a program launched by Texas Governor Greg Abbott to increase safety at the southern border of the state. Arrest data from the program shows that the number of males arrested is much higher than the number of females since the programs' inception in 2021."</span>),</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"By Olivia Dilley"</span>,</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Sex of arrested individual"</span>,</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of arrests"</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in geom_col(stat = "identity"): Ignoring unknown parameters: `stat`</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-analysisgraphics_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="ethnicity" class="level4">
<h4 class="anchored" data-anchor-id="ethnicity">Ethnicity:</h4>
<p>We’ll do the same procedure except using the ethnicity of the arrested person.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>olsethnicity <span class="ot">&lt;-</span> olsdata <span class="sc">|&gt;</span> </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ethnicity) <span class="sc">|&gt;</span> </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">appearances =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(appearances))</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>olsethnicity</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  ethnicity appearances
  &lt;chr&gt;           &lt;int&gt;
1 &lt;NA&gt;            41379
2 H               14302
3 N                2811
4 U                 143</code></pre>
</div>
</div>
<p>We can see that the vast majority of rows in the data set didn’t have an ethnicity listed - this is because the newer system, VERSA, includes ethnicity, but SPURS did not. But for the cases where an ethnicity was listed, the majority of arrested people were Hispanic.</p>
<section id="creating-a-graph-for-ethnicity-demographics" class="level5">
<h5 class="anchored" data-anchor-id="creating-a-graph-for-ethnicity-demographics">Creating a graph for ethnicity demographics</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(olsethnicity, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(ethnicity, appearances), <span class="at">y =</span> appearances)) <span class="sc">+</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Operation Lone Star arrests by ethnicity"</span>,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="fu">str_wrap</span>(<span class="st">"Arrest data from Operation Lone Star shows that the number of Hispanics arrested is much higher than the number of non-Hispanics since the programs' inception in 2021. Notable is the large number in the N/A category, which calls into question the practices used when recording data."</span>),</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"By Olivia Dilley"</span>,</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Ethnicity of arrested individual"</span>,</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of arrests"</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-analysisgraphics_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="age" class="level4">
<h4 class="anchored" data-anchor-id="age">Age:</h4>
<p>First we’ll call olsdata and group by the person’s age, summarize by appearances, and arrange in descending order to see what age’s have the most arrest instances. Then we’ll put that in a new bucket, olsage, for later reference.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>olsage <span class="ot">&lt;-</span> olsdata <span class="sc">|&gt;</span> </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(person_age) <span class="sc">|&gt;</span> </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">appearances =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(appearances)) </span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>olsage</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 81 × 2
   person_age appearances
        &lt;dbl&gt;       &lt;int&gt;
 1         NA        6119
 2         22        2462
 3         20        2457
 4         21        2378
 5         24        2354
 6         23        2341
 7         19        2321
 8         25        2206
 9         26        2069
10         27        2014
# ℹ 71 more rows</code></pre>
</div>
</div>
<p>Now, if you click through the data, you’ll see some obvious entering errors, like ages that are in the negatives and people that are between 1 and 943 years old. Because of this, we’ve decided to filter ages to between 10 and 100 to only incorporate cases that are most likely accurate age enterings.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>olsagerefined <span class="ot">&lt;-</span> olsage <span class="sc">|&gt;</span> </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">between</span> (person_age, <span class="dv">10</span>, <span class="dv">100</span>))</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>olsagerefined</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 69 × 2
   person_age appearances
        &lt;dbl&gt;       &lt;int&gt;
 1         22        2462
 2         20        2457
 3         21        2378
 4         24        2354
 5         23        2341
 6         19        2321
 7         25        2206
 8         26        2069
 9         27        2014
10         28        1985
# ℹ 59 more rows</code></pre>
</div>
</div>
<p>Once we have this data, we’ll make a simple scatter plot with it using ggplot and geom_point.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(olsagerefined, <span class="fu">aes</span>(<span class="at">x =</span> person_age, <span class="at">y =</span> appearances)) <span class="sc">+</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-analysisgraphics_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>What’s interesting about this graph is that it closely reflects the age-crime curve which shows the rate of criminal activity as it corresponds with age.</p>
<p>See <a href="https://pinkerton.com/our-insights/blog/age-crime-curve">Pinkerton’s Age-Crime Curve</a>.</p>
</section>
<section id="race" class="level4">
<h4 class="anchored" data-anchor-id="race">Race:</h4>
<p>Lastly for basic demographics, we’ll look at the race of people arrested in OLS.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>olsrace <span class="ot">&lt;-</span> olsdata <span class="sc">|&gt;</span> </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(person_race_abbr) <span class="sc">|&gt;</span> </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">appearances =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(appearances))</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>olsrace</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 2
  person_race_abbr appearances
  &lt;chr&gt;                  &lt;int&gt;
1 H                      44602
2 W                       8822
3 B                       4187
4 &lt;NA&gt;                     857
5 A                         98
6 U                         67
7 I                          2</code></pre>
</div>
</div>
<section id="creating-a-graph-for-race-demographics" class="level5">
<h5 class="anchored" data-anchor-id="creating-a-graph-for-race-demographics">Creating a graph for race demographics</h5>
<p>Now we’ll make a bar chart to check this out visually.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(olsrace, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(person_race_abbr, appearances), <span class="at">y =</span> appearances)) <span class="sc">+</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Operation Lone Star arrests by race"</span>,</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="fu">str_wrap</span>(<span class="st">"Arrest data from Operation Lone Star shows that the number of Hispanics arrested is much higher than any other race since the programs' inception in 2021."</span>),</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"By Olivia Dilley"</span>,</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Race of arrested individual"</span>,</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of arrests"</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-analysisgraphics_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We cans see Hispanics are still the most-arrested in the OLS database.</p>
<p>Let’s break these down by each race to see what crimes are being committed the most.</p>
</section>
</section>
</section>
<section id="breaking-down-offenders-charges-by-races" class="level3">
<h3 class="anchored" data-anchor-id="breaking-down-offenders-charges-by-races">Breaking down offenders’ charges by races</h3>
<section id="well-start-with-black-arrestees" class="level4">
<h4 class="anchored" data-anchor-id="well-start-with-black-arrestees">We’ll start with Black arrestees</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>blackarrests <span class="ot">&lt;-</span> cat_ols <span class="sc">|&gt;</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(person_race_abbr, charge_cat) <span class="sc">|&gt;</span> </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(person_race_abbr <span class="sc">==</span> <span class="st">"B"</span>) <span class="sc">|&gt;</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">appearances =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span> </span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(appearances))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'person_race_abbr'. You can override using
the `.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>blackarrests</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 11 × 3
# Groups:   person_race_abbr [1]
   person_race_abbr charge_cat                       appearances
   &lt;chr&gt;            &lt;chr&gt;                                  &lt;int&gt;
 1 B                Drug                                    1898
 2 B                Smuggling/Trafficking of Persons        1184
 3 B                Warrant                                  339
 4 B                Weapon                                   300
 5 B                Evasion/Fleeing                          249
 6 B                Unauthorized Use of Vehicle              100
 7 B                Trespassing                               41
 8 B                Tampering                                 34
 9 B                Organized Crime                           31
10 B                Money Laundering                          10
11 B                Conspiracy                                 1</code></pre>
</div>
</div>
<p>So Black people are most commonly getting arrested under OLS for drugs, then smuggling. Let’s make this a graph.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(blackarrests, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(charge_cat, appearances), <span class="at">y =</span> appearances)) <span class="sc">+</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Charge types for Black arrestees"</span>,</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="fu">str_wrap</span>(<span class="st">"Operation Lonestar arrest data shows Black people are being arrested mostly for drug and smuggling related charges."</span>),</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"By Olivia Dilley"</span>,</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of arrests"</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-analysisgraphics_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="now-white-arrests" class="level4">
<h4 class="anchored" data-anchor-id="now-white-arrests">Now White arrests</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>whitearrests <span class="ot">&lt;-</span> cat_ols <span class="sc">|&gt;</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(person_race_abbr, charge_cat) <span class="sc">|&gt;</span> </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(person_race_abbr <span class="sc">==</span> <span class="st">"W"</span>) <span class="sc">|&gt;</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">appearances =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span> </span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(appearances))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'person_race_abbr'. You can override using
the `.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>whitearrests</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 3
# Groups:   person_race_abbr [1]
   person_race_abbr charge_cat                       appearances
   &lt;chr&gt;            &lt;chr&gt;                                  &lt;int&gt;
 1 W                Drug                                    5045
 2 W                Smuggling/Trafficking of Persons        1416
 3 W                Warrant                                  786
 4 W                Evasion/Fleeing                          492
 5 W                Weapon                                   450
 6 W                Trespassing                              242
 7 W                Unauthorized Use of Vehicle              142
 8 W                Tampering                                127
 9 W                Organized Crime                           70
10 W                Money Laundering                          41
11 W                Immigration Other                          6
12 W                Conspiracy                                 5</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(whitearrests, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(charge_cat, appearances), <span class="at">y =</span> appearances)) <span class="sc">+</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Charge types for white arrestees"</span>,</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="fu">str_wrap</span>(<span class="st">"Operation Lonestar arrest data shows white people are being arrested mostly for drug and smuggling related charges."</span>),</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"By Olivia Dilley"</span>,</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of arrests"</span></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-analysisgraphics_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="now-hispanic-arrests" class="level4">
<h4 class="anchored" data-anchor-id="now-hispanic-arrests">Now Hispanic arrests</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>hispanicarrests <span class="ot">&lt;-</span> cat_ols <span class="sc">|&gt;</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(person_race_abbr, charge_cat) <span class="sc">|&gt;</span> </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(person_race_abbr <span class="sc">==</span> <span class="st">"H"</span>) <span class="sc">|&gt;</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">appearances =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span> </span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(appearances))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'person_race_abbr'. You can override using
the `.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>hispanicarrests</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13 × 3
# Groups:   person_race_abbr [1]
   person_race_abbr charge_cat                       appearances
   &lt;chr&gt;            &lt;chr&gt;                                  &lt;int&gt;
 1 H                Drug                                   15803
 2 H                Trespassing                            11033
 3 H                Smuggling/Trafficking of Persons        8178
 4 H                Evasion/Fleeing                         3814
 5 H                Warrant                                 2988
 6 H                Weapon                                  1174
 7 H                Unauthorized Use of Vehicle              599
 8 H                Tampering                                530
 9 H                Organized Crime                          215
10 H                Money Laundering                         126
11 H                Immigration Other                        123
12 H                Conspiracy                                14
13 H                Other                                      5</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(hispanicarrests, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(charge_cat, appearances), <span class="at">y =</span> appearances)) <span class="sc">+</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Charge types for Hispanic arrestees"</span>,</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="fu">str_wrap</span>(<span class="st">"Operation Lonestar arrest data shows Hispanic people are being arrested mostly for drug and smuggling related charges."</span>),</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"By Olivia Dilley"</span>,</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of arrests"</span></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-analysisgraphics_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="now-asian-arrests" class="level4">
<h4 class="anchored" data-anchor-id="now-asian-arrests">Now Asian arrests</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>asianarrests <span class="ot">&lt;-</span> cat_ols <span class="sc">|&gt;</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(person_race_abbr, charge_cat) <span class="sc">|&gt;</span> </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(person_race_abbr <span class="sc">==</span> <span class="st">"A"</span>) <span class="sc">|&gt;</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">appearances =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span> </span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(appearances))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'person_race_abbr'. You can override using
the `.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>asianarrests</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
# Groups:   person_race_abbr [1]
  person_race_abbr charge_cat                       appearances
  &lt;chr&gt;            &lt;chr&gt;                                  &lt;int&gt;
1 A                Drug                                      56
2 A                Smuggling/Trafficking of Persons          12
3 A                Evasion/Fleeing                            9
4 A                Trespassing                                9
5 A                Warrant                                    7
6 A                Weapon                                     5</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(asianarrests, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(charge_cat, appearances), <span class="at">y =</span> appearances)) <span class="sc">+</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Charge types for Asian arrestees"</span>,</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="fu">str_wrap</span>(<span class="st">"Operation Lonestar arrest data shows Asian people are being arrested mostly for drug and smuggling related charges."</span>),</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"By Olivia Dilley"</span>,</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of arrests"</span></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-analysisgraphics_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="now-well-look-at-who-is-doing-the-arresting-and-where" class="level3">
<h3 class="anchored" data-anchor-id="now-well-look-at-who-is-doing-the-arresting-and-where">Now we’ll look at who is doing the arresting and where?</h3>
<p>We’ll look into officers, ID, and county.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>olsofficers <span class="ot">&lt;-</span> olsdata <span class="sc">|&gt;</span> </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(arresting_officer, officer_id, arrest_county) <span class="sc">|&gt;</span> </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">appearances =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(appearances))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'arresting_officer', 'officer_id'. You can
override using the `.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>olsofficers</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7,500 × 4
# Groups:   arresting_officer, officer_id [3,159]
   arresting_officer officer_id arrest_county appearances
   &lt;chr&gt;                  &lt;dbl&gt; &lt;chr&gt;               &lt;int&gt;
 1 &lt;NA&gt;                   15952 Maverick              392
 2 &lt;NA&gt;                   15532 Maverick              339
 3 &lt;NA&gt;                   15834 Maverick              287
 4 Derrick Hinojosa          NA Cameron               278
 5 &lt;NA&gt;                   11522 Maverick              259
 6 Jose Mendoza              NA Cameron               233
 7 &lt;NA&gt;                   13362 Maverick              218
 8 &lt;NA&gt;                   11689 Maverick              216
 9 Jose Delafuente           NA Cameron               213
10 David Poland              NA Nueces                210
# ℹ 7,490 more rows</code></pre>
</div>
</div>
<p>We can see that the top 3 officers are not identified by name, meaning they are from the VERSA dataset (which removed officer name identification).</p>
</section>
</section>
<section id="categories" class="level2">
<h2 class="anchored" data-anchor-id="categories">Categories</h2>
<p>Now we’ll be using those categories we made to look into the smuggling and drug categories.</p>
<section id="drug" class="level3">
<h3 class="anchored" data-anchor-id="drug">Drug</h3>
<p>Operation Lone Star focused heavily on stopping drugs from crossing the border. Lauren wanted us to look at what types of drug-related charges were happening. Because the discourse around OLS was heavily focused on Fentanyl, we focused on that to see whether or not what Abbott’s administration was saying about what OLS was accomplishing was true.</p>
<section id="what-kind-of-drug-charges-are-happening-are-many-fentanyl-related-like-abbott-claims" class="level4">
<h4 class="anchored" data-anchor-id="what-kind-of-drug-charges-are-happening-are-many-fentanyl-related-like-abbott-claims">What kind of drug charges are happening? Are many Fentanyl-related like Abbott claims?</h4>
<p>Let’s look at the drug charge category and break it down by type of drug. We used drug statute codes from the <a href="https://statutes.capitol.texas.gov/Docs/HS/htm/HS.481.htm">Texas’ Health and Safety Code</a> and the <a href="https://www.dea.gov/drug-information/drug-scheduling.">Drug Enforcement Agency</a> to categorize each drug.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>drug_ols <span class="ot">&lt;-</span> cat_ols <span class="sc">|&gt;</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(charge) <span class="sc">|&gt;</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(charge_cat <span class="sc">==</span> <span class="st">"Drug"</span>) <span class="sc">|&gt;</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">drug_type =</span> <span class="fu">case_when</span>(</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(charge, <span class="st">"Mari|MARI|Marj|MARJ"</span>) <span class="sc">~</span> <span class="st">"Marijuana"</span>,</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(charge, <span class="st">"Fent|FENT|1-B"</span>) <span class="sc">~</span> <span class="st">"Fentanyl"</span>,</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(charge, <span class="st">"Cocaine|COCAINE"</span>) <span class="sc">~</span> <span class="st">"Cocaine"</span>,</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(charge, <span class="st">"Meth|METH"</span>) <span class="sc">~</span> <span class="st">"Crystal Meth"</span>,</span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(charge, <span class="st">"1a|1-A|LSD"</span>)  <span class="sc">~</span> <span class="st">"LSD"</span>,</span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(charge, <span class="st">"Heroin|HEROIN"</span>) <span class="sc">~</span> <span class="st">"Heroin"</span>),</span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">default. =</span> <span class="cn">NA</span>,</span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb48-15"><a href="#cb48-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">fentanyl =</span> <span class="fu">case_when</span>(</span>
<span id="cb48-16"><a href="#cb48-16" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(charge, <span class="st">"Fent|FENT|1-B|Schedule Ii/"</span>) <span class="sc">~</span> <span class="st">"YES"</span>),        </span>
<span id="cb48-17"><a href="#cb48-17" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb48-18"><a href="#cb48-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">default. =</span> <span class="cn">NA</span>,</span>
<span id="cb48-19"><a href="#cb48-19" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb48-20"><a href="#cb48-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">marijuana =</span> <span class="fu">case_when</span>(</span>
<span id="cb48-21"><a href="#cb48-21" aria-hidden="true" tabindex="-1"></a>        <span class="fu">str_detect</span>(charge, <span class="st">"Mari|MARI|Marj|MARJ|Drug Test|Schedule I/"</span>) <span class="sc">~</span> <span class="st">"YES"</span>),</span>
<span id="cb48-22"><a href="#cb48-22" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb48-23"><a href="#cb48-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">default. =</span> <span class="cn">NA</span>,</span>
<span id="cb48-24"><a href="#cb48-24" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb48-25"><a href="#cb48-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">drug_weapon =</span> <span class="fu">case_when</span>(</span>
<span id="cb48-26"><a href="#cb48-26" aria-hidden="true" tabindex="-1"></a>          <span class="fu">str_detect</span>(charge, <span class="st">"DRUG/WEAPON"</span>) <span class="sc">~</span> <span class="st">"YES"</span>),</span>
<span id="cb48-27"><a href="#cb48-27" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb48-28"><a href="#cb48-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">default. =</span> <span class="cn">NA</span>   )</span>
<span id="cb48-29"><a href="#cb48-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-30"><a href="#cb48-30" aria-hidden="true" tabindex="-1"></a>drug_ols <span class="sc">|&gt;</span> <span class="fu">count</span>(drug_type, fentanyl, marijuana, drug_weapon)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 234 × 6
# Groups:   charge [234]
   charge                         drug_type fentanyl marijuana drug_weapon     n
   &lt;chr&gt;                          &lt;chr&gt;     &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;       &lt;int&gt;
 1 (FENTANYL) POSS CS PG 1 &lt;1G    Fentanyl  YES      &lt;NA&gt;      &lt;NA&gt;            1
 2 (HEROIN) POSS CS PG 1 &lt;1G      Heroin    &lt;NA&gt;     &lt;NA&gt;      &lt;NA&gt;            1
 3 Conspiracy To Possess With In… &lt;NA&gt;      &lt;NA&gt;     &lt;NA&gt;      &lt;NA&gt;          201
 4 Conspiracy To Sale/Manfct/Dis… &lt;NA&gt;      &lt;NA&gt;     &lt;NA&gt;      &lt;NA&gt;          122
 5 Controlled Substance Offenses… &lt;NA&gt;      &lt;NA&gt;     &lt;NA&gt;      &lt;NA&gt;          110
 6 Controlled Substance Offenses… &lt;NA&gt;      &lt;NA&gt;     &lt;NA&gt;      &lt;NA&gt;           11
 7 Del Cont Subs/Marij To Minor   Marijuana &lt;NA&gt;     YES       &lt;NA&gt;            1
 8 Del Marij 1/4 oz &lt;5 lbs Use C… Marijuana &lt;NA&gt;     YES       &lt;NA&gt;            1
 9 Del Marij &lt;1/4 oz DFZ IAT      Marijuana &lt;NA&gt;     YES       &lt;NA&gt;            1
10 Del Marij &lt;= 1/4 OZ            Marijuana &lt;NA&gt;     YES       &lt;NA&gt;            3
# ℹ 224 more rows</code></pre>
</div>
</div>
<p>Originally, we tried categorizing the charges by type of drug, but this doesn’t work out well because of the different codes used to separate each drug. So we decided to focus on any charges that could be related to fentanyl (as some are unclear) to answer our question. We also focused on marijuana charges, one of the more recurring drug offenses. Then we made a column called drug_weapon for all charges under the drug category that could also be weapons charges.</p>
<p>Key for Drug Categories:</p>
<ul>
<li><strong>Poss Cs Pg</strong> = Possession of Controlled Substance in Penalty Group</li>
<li><strong>Fentanyl</strong>= Group 1-B (any type of fentanyl)</li>
<li><strong>Drug schedule</strong>= Can refer to a group of drugs (for example, fentanyl can be found in schedule II drugs) - <strong>1-A</strong> = LSD as well as any of its salts, isomers, and salts of isomers.</li>
<li><strong>OFFENSE: FALSIFICATION OF DRUG TEST RESULTS</strong> = Can refer to failing an authorized marijuana drug test Under Sec. 481.133., we noted that as “YES” under the marijuana column.</li>
</ul>
<p>Let’s count the amount of drug charges that can be related to fentanyl or marijuana:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>drug_ols_analysis <span class="ot">&lt;-</span> drug_ols <span class="sc">|&gt;</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">drug_charge =</span> <span class="fu">case_when</span>(</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_detect</span>(fentanyl, <span class="st">"YES"</span>) <span class="sc">~</span> <span class="st">"Fentanyl"</span>,</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_detect</span>(marijuana, <span class="st">"YES"</span>) <span class="sc">~</span> <span class="st">"Marijuana"</span>,</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">.default =</span> <span class="st">"Other"</span>   )) </span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>drug_ols_analysis_new <span class="ot">&lt;-</span> drug_ols_analysis <span class="sc">|&gt;</span> <span class="fu">count</span>(drug_charge) <span class="sc">|&gt;</span> </span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rename</span>(<span class="at">charge_count =</span> n)</span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>drug_ols_analysis_new</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  drug_charge charge_count
  &lt;chr&gt;              &lt;int&gt;
1 Fentanyl            1571
2 Marijuana           9491
3 Other              12171</code></pre>
</div>
</div>
<p>Then we decided to make a simple bar graph to show the amount of charges that can be related to Fentanyl or Marijuana.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(drug_ols_analysis_new,</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> charge_count, <span class="at">y =</span>  drug_charge)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> charge_count), </span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">hjust =</span> <span class="fl">1.2</span>,</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(</span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"What types of drugs does Operation Lone Star target?"</span>,</span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Number of Charges"</span>,</span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Type of Drug Charge"</span>,</span>
<span id="cb52-12"><a href="#cb52-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="fu">str_wrap</span>(<span class="st">"This analysis looked at fentanyl and marijuana related drug charges. Most drug charges were not related to either fentanyl or marijuana. However, drug charges are recorded differently in the data, so further anaylsis is needed to determine if this reflects the total number for each type of drug."</span>),</span>
<span id="cb52-13"><a href="#cb52-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Source = Operation Lone Star Data"</span></span>
<span id="cb52-14"><a href="#cb52-14" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-analysisgraphics_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="data-takeaways-for-drug-charges" class="level4">
<h4 class="anchored" data-anchor-id="data-takeaways-for-drug-charges">Data Takeaways for Drug Charges</h4>
<ul>
<li><p>At least 1,571 charges in both OLS datasets are related to possession/manufacturing of Fentanyl. This is lower than the amount of charges related to Marijuana, which are at least 9,491.</p></li>
<li><p>Overall, Fentanyl charges identified in this analysis account for little over 6% of all drug charges, while Marijuana charges account for little over 40% of the drug charges (from the total 23,233 drug charges identified).</p></li>
</ul>
</section>
</section>
<section id="solo-drug-charges" class="level3">
<h3 class="anchored" data-anchor-id="solo-drug-charges">Solo Drug Charges</h3>
<p>When talking to Lauren about the importance of drug charges within Operation Lone Star, she mentioned separating solo drug charges from the data set. To do this, we filtered and looked at single drug charges in order to look at what drugs were being associated to each charge. This helps us narrow down drug charges in the analysis.</p>
<p>Now let’s look at the individuals being charged for drug charges:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>cat_ols <span class="sc">|&gt;</span>   <span class="fu">filter</span>(charge_cat <span class="sc">==</span> <span class="st">"Drug"</span>) <span class="sc">|&gt;</span>   <span class="fu">count</span>(charge_count)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   charge_count     n
          &lt;dbl&gt; &lt;int&gt;
 1            1 22819
 2            2   353
 3            3    42
 4            4     9
 5            5     4
 6            6     1
 7            7     1
 8            8     2
 9           11     1
10           60     1</code></pre>
</div>
</div>
<p>Data Takeaways: Most charges are solo charges.</p>
<p>Now let’s look at the solo charges and what drugs they are related too.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>solo_drug_ols <span class="ot">&lt;-</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  cat_ols <span class="sc">|&gt;</span>   <span class="fu">group_by</span>(charge, charge_count) <span class="sc">|&gt;</span>   <span class="fu">filter</span>(charge_cat <span class="sc">==</span> <span class="st">"Drug"</span>) <span class="sc">|&gt;</span> <span class="fu">mutate</span>(</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">fentanyl =</span> <span class="fu">case_when</span>(</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(charge, <span class="st">"Fent|FENT|1-B|Schedule Ii/"</span>) <span class="sc">~</span> <span class="st">"YES"</span>),</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">marijuana =</span> <span class="fu">case_when</span>(</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(charge, <span class="st">"Mari|MARI|Marj|MARJ|Drug Test|Schedule I/"</span>) <span class="sc">~</span> <span class="st">"YES"</span>),</span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">default. =</span> <span class="cn">NA</span>,) <span class="sc">|&gt;</span></span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(charge_count <span class="sc">==</span> <span class="st">"1"</span>) </span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a>solo_drug_ols <span class="sc">|&gt;</span></span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(charge, charge_count, fentanyl, marijuana)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 230 × 5
# Groups:   charge, charge_count [230]
   charge                                  charge_count fentanyl marijuana     n
   &lt;chr&gt;                                          &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;     &lt;int&gt;
 1 (FENTANYL) POSS CS PG 1 &lt;1G                        1 YES      &lt;NA&gt;          1
 2 (HEROIN) POSS CS PG 1 &lt;1G                          1 &lt;NA&gt;     &lt;NA&gt;          1
 3 Conspiracy To Possess With Intent To D…            1 &lt;NA&gt;     &lt;NA&gt;        192
 4 Conspiracy To Sale/Manfct/Dist Control…            1 &lt;NA&gt;     &lt;NA&gt;        121
 5 Controlled Substance Offenses-Felony               1 &lt;NA&gt;     &lt;NA&gt;        103
 6 Controlled Substance Offenses-Misdemea…            1 &lt;NA&gt;     &lt;NA&gt;         11
 7 Del Marij 1/4 oz &lt;5 lbs Use Child                  1 &lt;NA&gt;     YES           1
 8 Del Marij &lt;1/4 oz DFZ IAT                          1 &lt;NA&gt;     YES           1
 9 Del Marij &lt;= 1/4 OZ                                1 &lt;NA&gt;     YES           3
10 Del Marij &lt;= 5 lbs &gt; 1/4 oz                        1 &lt;NA&gt;     YES          15
# ℹ 220 more rows</code></pre>
</div>
</div>
<p>Now we’ll group by what type of drug.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>solo_drug_type <span class="ot">&lt;-</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  solo_drug_ols <span class="sc">|&gt;</span>   <span class="fu">ungroup</span>() <span class="sc">|&gt;</span>   <span class="fu">mutate</span>(</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">drug_charge_s =</span> <span class="fu">case_when</span>(</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(fentanyl, <span class="st">"YES"</span>) <span class="sc">~</span> <span class="st">"Fentanyl"</span>,</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(marijuana, <span class="st">"YES"</span>) <span class="sc">~</span> <span class="st">"Marijuana"</span>,</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">.default =</span> <span class="st">"Other"</span></span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a>solo_drug_type_chart <span class="ot">&lt;-</span> solo_drug_type <span class="sc">|&gt;</span>   <span class="fu">count</span>(drug_charge_s) <span class="sc">|&gt;</span> </span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">charge_count =</span> n)</span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a>solo_drug_type_chart</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  drug_charge_s charge_count
  &lt;chr&gt;                &lt;int&gt;
1 Fentanyl              1506
2 Marijuana             9459
3 Other                11854</code></pre>
</div>
</div>
<p>Now we’ll make a chart to look at this data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(solo_drug_type_chart,</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> charge_count, <span class="at">y =</span>  drug_charge_s)</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span>  </span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span> </span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> charge_count), </span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">hjust =</span> <span class="fl">1.3</span>,</span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"What do solo drug charges look like under Operation Lone Star?"</span>,</span>
<span id="cb59-10"><a href="#cb59-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Number of Charges"</span>,</span>
<span id="cb59-11"><a href="#cb59-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Type of Drug Charge"</span>,</span>
<span id="cb59-12"><a href="#cb59-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="fu">str_wrap</span>(</span>
<span id="cb59-13"><a href="#cb59-13" aria-hidden="true" tabindex="-1"></a>      <span class="st">"This analysis looked at fentanyl and marijuana related drug charges. Most drug charges were not related to either fentanyl or marijuana. However, drug charges for the same type of drug are recorded differently in the data, so further anaylsis is needed to determine if this reflects the total number for each type of drug."</span></span>
<span id="cb59-14"><a href="#cb59-14" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb59-15"><a href="#cb59-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Source = Operation Lone Star Data"</span></span>
<span id="cb59-16"><a href="#cb59-16" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-analysisgraphics_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="where-are-solo-drug-charges-located" class="level4">
<h4 class="anchored" data-anchor-id="where-are-solo-drug-charges-located">Where are solo drug charges located?</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>solo_drug_ols <span class="sc">|&gt;</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(arrest_county) <span class="sc">|&gt;</span>  </span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">appearances =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span> </span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(appearances))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 64 × 2
   arrest_county appearances
   &lt;chr&gt;               &lt;int&gt;
 1 Hidalgo              3568
 2 Cameron              2291
 3 Starr                1422
 4 El Paso              1373
 5 Webb                 1096
 6 Ector                1084
 7 San Patricio          959
 8 Tom Green             800
 9 Pecos                 740
10 Uvalde                708
# ℹ 54 more rows</code></pre>
</div>
</div>
<p>Let’s look at Ector, the 6th county with the most solo drug charges not on the border.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>ector_example <span class="ot">&lt;-</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>  solo_drug_ols <span class="sc">|&gt;</span>   <span class="fu">ungroup</span>() <span class="sc">|&gt;</span>   <span class="fu">filter</span>(arrest_county <span class="sc">==</span> <span class="st">"Ector"</span>) <span class="sc">|&gt;</span>   <span class="fu">mutate</span>(</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">drug_charge_s =</span> <span class="fu">case_when</span>(</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(fentanyl, <span class="st">"YES"</span>) <span class="sc">~</span> <span class="st">"fentanyl"</span>,</span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(marijuana, <span class="st">"YES"</span>) <span class="sc">~</span> <span class="st">"marijuana"</span>,</span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">.default =</span> <span class="st">"other"</span></span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>  ) </span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a>ector_example <span class="sc">|&gt;</span>   <span class="fu">count</span>(drug_charge_s)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  drug_charge_s     n
  &lt;chr&gt;         &lt;int&gt;
1 fentanyl         72
2 marijuana       404
3 other           608</code></pre>
</div>
</div>
<p>Data Takeaway: Most of the solo drug charges in Ector county are unrelated to fentanyl. Notably, Odessa is inside Ector county.</p>
</section>
</section>
<section id="smuggling" class="level3">
<h3 class="anchored" data-anchor-id="smuggling">Smuggling</h3>
<section id="breaking-down-the-smuggling-charge-category" class="level4">
<h4 class="anchored" data-anchor-id="breaking-down-the-smuggling-charge-category">Breaking down the Smuggling charge category</h4>
<p>Lauren has a theory that Black people in areas like Houston are being tricked into smuggling people across the border. We want to look at the smuggling category and break down how many offenses are from Black people and where those offenses took place so we can test that theory.</p>
<p>First we’ll look at the smuggling charges for all races and tally them to see who is getting arrested for smuggling the most.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>cat_ols <span class="sc">|&gt;</span> </span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(person_race_abbr, charge_cat) <span class="sc">|&gt;</span> </span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(charge_cat <span class="sc">==</span> <span class="st">"Smuggling/Trafficking of Persons"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">appearances =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span> </span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(appearances))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'person_race_abbr'. You can override using
the `.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
# Groups:   person_race_abbr [6]
  person_race_abbr charge_cat                       appearances
  &lt;chr&gt;            &lt;chr&gt;                                  &lt;int&gt;
1 H                Smuggling/Trafficking of Persons        8178
2 W                Smuggling/Trafficking of Persons        1416
3 B                Smuggling/Trafficking of Persons        1184
4 &lt;NA&gt;             Smuggling/Trafficking of Persons         173
5 A                Smuggling/Trafficking of Persons          12
6 U                Smuggling/Trafficking of Persons           2</code></pre>
</div>
</div>
<p>Lauren thinks this number of Black smuggling offenses is still substantial for Texas’ population demographics, despite it only being 3rd highest behind Hispanic and White.</p>
</section>
</section>
</section>
<section id="smuggling-by-county-and-race" class="level2">
<h2 class="anchored" data-anchor-id="smuggling-by-county-and-race">Smuggling by county and race</h2>
<p>Let’s look at all races smuggling charges by county to see how many smuggling charges there are for each race in each specific county.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>smuggle_ols <span class="ot">&lt;-</span> cat_ols <span class="sc">|&gt;</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(person_race_abbr, charge_cat, arrest_county) <span class="sc">|&gt;</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">appearances =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(<span class="fu">desc</span>(appearances)) <span class="sc">|&gt;</span></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(charge_cat <span class="sc">==</span> <span class="st">"Smuggling/Trafficking of Persons"</span>) <span class="sc">|&gt;</span></span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(<span class="sc">!</span>charge_cat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'person_race_abbr', 'charge_cat'. You can
override using the `.groups` argument.
Adding missing grouping variables: `charge_cat`</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>smuggle_ols</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 163 × 4
# Groups:   person_race_abbr, charge_cat [6]
   charge_cat                       person_race_abbr arrest_county appearances
   &lt;chr&gt;                            &lt;chr&gt;            &lt;chr&gt;               &lt;int&gt;
 1 Smuggling/Trafficking of Persons H                Kinney               1347
 2 Smuggling/Trafficking of Persons H                El Paso              1230
 3 Smuggling/Trafficking of Persons H                Hidalgo               884
 4 Smuggling/Trafficking of Persons H                Webb                  555
 5 Smuggling/Trafficking of Persons H                Val Verde             492
 6 Smuggling/Trafficking of Persons H                Uvalde                486
 7 Smuggling/Trafficking of Persons H                Maverick              475
 8 Smuggling/Trafficking of Persons B                Kinney                448
 9 Smuggling/Trafficking of Persons H                Zavala                399
10 Smuggling/Trafficking of Persons W                Kinney                305
# ℹ 153 more rows</code></pre>
</div>
</div>
<p>The most common is Hispanic people smuggling in areas near the border, like Kinney and El Paso county. Black smuggling in Kinney is also in the top 10.</p>
</section>
<section id="breaking-down-the-black-smuggling-category-by-county-to-test-laurens-theory" class="level2">
<h2 class="anchored" data-anchor-id="breaking-down-the-black-smuggling-category-by-county-to-test-laurens-theory">Breaking down the Black smuggling category by county to test Lauren’s theory</h2>
<p>Let’s break down the smuggling category by county for Black offenders to see where they are most commonly being arrested (not where they are from necessarily).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>b_smuggling <span class="ot">&lt;-</span> cat_ols <span class="sc">|&gt;</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(arrest_county, arrest_state, person_race_abbr, charge_cat) <span class="sc">|&gt;</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(person_race_abbr <span class="sc">==</span> <span class="st">"B"</span>, charge_cat <span class="sc">==</span> <span class="st">"Smuggling/Trafficking of Persons"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">appearances =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span> </span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(appearances))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'arrest_county', 'arrest_state',
'person_race_abbr'. You can override using the `.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>b_smuggling</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 38 × 5
# Groups:   arrest_county, arrest_state, person_race_abbr [38]
   arrest_county arrest_state person_race_abbr charge_cat            appearances
   &lt;chr&gt;         &lt;chr&gt;        &lt;chr&gt;            &lt;chr&gt;                       &lt;int&gt;
 1 Kinney        TEXAS        B                Smuggling/Traffickin…         448
 2 Val Verde     TEXAS        B                Smuggling/Traffickin…         130
 3 Maverick      TEXAS        B                Smuggling/Traffickin…         109
 4 Uvalde        TEXAS        B                Smuggling/Traffickin…          94
 5 Zavala        TEXAS        B                Smuggling/Traffickin…          73
 6 Edwards       TEXAS        B                Smuggling/Traffickin…          66
 7 Dimmit        TEXAS        B                Smuggling/Traffickin…          48
 8 Sutton        TEXAS        B                Smuggling/Traffickin…          34
 9 El Paso       TEXAS        B                Smuggling/Traffickin…          23
10 La Salle      TEXAS        B                Smuggling/Traffickin…          22
# ℹ 28 more rows</code></pre>
</div>
</div>
<section id="well-make-a-graph-for-this-to-visualize-it-better." class="level4">
<h4 class="anchored" data-anchor-id="well-make-a-graph-for-this-to-visualize-it-better.">We’ll make a graph for this to visualize it better.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(b_smuggling, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(arrest_county, appearances), <span class="at">y =</span> appearances)) <span class="sc">+</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Black smuggling arrests by county"</span>,</span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="fu">str_wrap</span>(<span class="st">"Operation Lonestar arrest data shows Black people are being arrested for smuggling charges in these counties."</span>),</span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"By Olivia Dilley"</span>,</span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb75-9"><a href="#cb75-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of arrests"</span></span>
<span id="cb75-10"><a href="#cb75-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-analysisgraphics_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="now-lets-see-the-breakdowns-for-other-races-starting-with-white-smuggling-arrests." class="level3">
<h3 class="anchored" data-anchor-id="now-lets-see-the-breakdowns-for-other-races-starting-with-white-smuggling-arrests.">Now let’s see the breakdowns for other races, starting with white smuggling arrests.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>w_smuggling <span class="ot">&lt;-</span> cat_ols <span class="sc">|&gt;</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(arrest_county, arrest_state, person_race_abbr, charge_cat) <span class="sc">|&gt;</span></span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(person_race_abbr <span class="sc">==</span> <span class="st">"W"</span>, charge_cat <span class="sc">==</span> <span class="st">"Smuggling/Trafficking of Persons"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">appearances =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span> </span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(appearances))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'arrest_county', 'arrest_state',
'person_race_abbr'. You can override using the `.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>w_smuggling</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 47 × 5
# Groups:   arrest_county, arrest_state, person_race_abbr [47]
   arrest_county arrest_state person_race_abbr charge_cat            appearances
   &lt;chr&gt;         &lt;chr&gt;        &lt;chr&gt;            &lt;chr&gt;                       &lt;int&gt;
 1 Kinney        TEXAS        W                Smuggling/Traffickin…         305
 2 El Paso       TEXAS        W                Smuggling/Traffickin…         230
 3 Hidalgo       TEXAS        W                Smuggling/Traffickin…         113
 4 Val Verde     TEXAS        W                Smuggling/Traffickin…         104
 5 Maverick      TEXAS        W                Smuggling/Traffickin…          87
 6 Uvalde        TEXAS        W                Smuggling/Traffickin…          79
 7 Zavala        TEXAS        W                Smuggling/Traffickin…          70
 8 Edwards       TEXAS        W                Smuggling/Traffickin…          50
 9 Webb          TEXAS        W                Smuggling/Traffickin…          45
10 Dimmit        TEXAS        W                Smuggling/Traffickin…          43
# ℹ 37 more rows</code></pre>
</div>
</div>
<section id="and-well-make-a-plot-for-this-too." class="level4">
<h4 class="anchored" data-anchor-id="and-well-make-a-plot-for-this-too.">And we’ll make a plot for this too.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(w_smuggling, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(arrest_county, appearances), <span class="at">y =</span> appearances)) <span class="sc">+</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"White smuggling arrests by county"</span>,</span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="fu">str_wrap</span>(<span class="st">"Operation Lonestar arrest data shows white people are being arrested for smuggling charges in these counties."</span>),</span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"By Olivia Dilley"</span>,</span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb80-9"><a href="#cb80-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of arrests"</span></span>
<span id="cb80-10"><a href="#cb80-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-analysisgraphics_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="now-lets-see-the-hispanic-breakdown." class="level3">
<h3 class="anchored" data-anchor-id="now-lets-see-the-hispanic-breakdown.">Now let’s see the Hispanic breakdown.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>h_smuggling <span class="ot">&lt;-</span> cat_ols <span class="sc">|&gt;</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(arrest_county, arrest_state, person_race_abbr, charge_cat) <span class="sc">|&gt;</span></span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(person_race_abbr <span class="sc">==</span> <span class="st">"H"</span>, charge_cat <span class="sc">==</span> <span class="st">"Smuggling/Trafficking of Persons"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">appearances =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span> </span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(appearances))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'arrest_county', 'arrest_state',
'person_race_abbr'. You can override using the `.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>h_smuggling</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 46 × 5
# Groups:   arrest_county, arrest_state, person_race_abbr [46]
   arrest_county arrest_state person_race_abbr charge_cat            appearances
   &lt;chr&gt;         &lt;chr&gt;        &lt;chr&gt;            &lt;chr&gt;                       &lt;int&gt;
 1 Kinney        TEXAS        H                Smuggling/Traffickin…        1347
 2 El Paso       TEXAS        H                Smuggling/Traffickin…        1230
 3 Hidalgo       TEXAS        H                Smuggling/Traffickin…         884
 4 Webb          TEXAS        H                Smuggling/Traffickin…         555
 5 Val Verde     TEXAS        H                Smuggling/Traffickin…         492
 6 Uvalde        TEXAS        H                Smuggling/Traffickin…         486
 7 Maverick      TEXAS        H                Smuggling/Traffickin…         475
 8 Zavala        TEXAS        H                Smuggling/Traffickin…         399
 9 Starr         TEXAS        H                Smuggling/Traffickin…         267
10 Edwards       TEXAS        H                Smuggling/Traffickin…         251
# ℹ 36 more rows</code></pre>
</div>
</div>
<section id="now-well-make-a-plot." class="level4">
<h4 class="anchored" data-anchor-id="now-well-make-a-plot.">Now we’ll make a plot.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(h_smuggling, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(arrest_county, appearances), <span class="at">y =</span> appearances)) <span class="sc">+</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Hispanic smuggling arrests by county"</span>,</span>
<span id="cb85-6"><a href="#cb85-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="fu">str_wrap</span>(<span class="st">"Operation Lonestar arrest data shows Hispanic people are being arrested for smuggling charges in these counties."</span>),</span>
<span id="cb85-7"><a href="#cb85-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"By Olivia Dilley"</span>,</span>
<span id="cb85-8"><a href="#cb85-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb85-9"><a href="#cb85-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of arrests"</span></span>
<span id="cb85-10"><a href="#cb85-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-analysisgraphics_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="kinney" class="level3">
<h3 class="anchored" data-anchor-id="kinney">Kinney</h3>
<p>Across the board, Kinney has the highest smuggling arrests in each race, so it doesn’t seem like Black arrests are more common there than any other race. Regardless, we looked into the breakdown of arrests in Kinney county for Black people charged with smuggling crimes just to see if anything stuck out.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>kinney_b_smuggling <span class="ot">&lt;-</span> cat_ols <span class="sc">|&gt;</span> </span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(arrest_county, arrest_state, person_race_abbr, charge_cat) <span class="sc">|&gt;</span> </span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(arrest_county <span class="sc">==</span> <span class="st">"Kinney"</span>, person_race_abbr <span class="sc">==</span> <span class="st">"B"</span>, charge_cat <span class="sc">==</span> <span class="st">"Smuggling/Trafficking of Persons"</span>) </span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a>kinney_b_smuggling</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 448 × 26
# Groups:   arrest_county, arrest_state, person_race_abbr, charge_cat [1]
   primary_key charge              charge_count ethnicity charge_date person_age
   &lt;chr&gt;       &lt;chr&gt;                      &lt;dbl&gt; &lt;chr&gt;     &lt;date&gt;           &lt;dbl&gt;
 1 TX202356    Smuggling of Perso…            5 N         2023-01-21          30
 2 TX202356    Smuggling of Perso…            2 N         2023-01-21          30
 3 TX2023105   Smuggling of Perso…            3 N         2023-02-06          27
 4 TX2023288   Smuggling of Perso…            1 N         2023-02-24          21
 5 TX2023289   Smuggling of Perso…            1 N         2023-02-24          22
 6 TX2023291   Smuggling of Perso…            3 N         2023-02-24          20
 7 TX2023355   Smuggling of Perso…            4 N         2023-02-25          NA
 8 TX2023437   Smuggling of Perso…            5 N         2023-02-14          42
 9 TX2023479   Smuggling of Perso…            5 N         2023-03-04          NA
10 TX2023916   Smuggling of Perso…            7 N         2023-03-18          38
# ℹ 438 more rows
# ℹ 20 more variables: person_first_name &lt;chr&gt;, person_second_name &lt;chr&gt;,
#   person_third_name &lt;chr&gt;, person_last_name &lt;chr&gt;, officer_id &lt;dbl&gt;,
#   arrest_county &lt;chr&gt;, code &lt;chr&gt;, severity_code &lt;chr&gt;,
#   severity_code_clean &lt;chr&gt;, person_race_abbr &lt;chr&gt;,
#   person_gender_abbr &lt;chr&gt;, arrest_state &lt;chr&gt;, arrest_division &lt;chr&gt;,
#   arrest_id &lt;dbl&gt;, arrest_urn &lt;chr&gt;, arresting_officer &lt;chr&gt;, …</code></pre>
</div>
</div>
<p>We can make a plot to look into the arrests over time to see if any dates had a much higher number of arrests than others.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(kinney_b_smuggling, <span class="fu">aes</span>(<span class="at">x=</span>charge_date, <span class="at">y=</span>charge_count)) <span class="sc">+</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Black smuggling arrests over time in Kinney County"</span>,</span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="fu">str_wrap</span>(<span class="st">"Operation Lonestar arrest data shows Black people are being arrested in Kinney for smuggling charges 4x as much as in any other county in OLS parameters. This breakdown shows those arrests over time."</span>),</span>
<span id="cb88-6"><a href="#cb88-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"By Olivia Dilley"</span>,</span>
<span id="cb88-7"><a href="#cb88-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Date"</span>,</span>
<span id="cb88-8"><a href="#cb88-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Charges"</span></span>
<span id="cb88-9"><a href="#cb88-9" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-analysisgraphics_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Because Kinney is the highest across all races, and the arrests don’t very super significantly over time, we didn’t see anything stand out from the data.</p>
</section>
</section>
<section id="lets-compare-percentages-of-arrests-by-races-with-tabyls" class="level2">
<h2 class="anchored" data-anchor-id="lets-compare-percentages-of-arrests-by-races-with-tabyls">Let’s compare percentages of arrests by races with tabyls</h2>
<p>We’ll make some tables where we can look at percentages of arrests by race for each county, officers, etc.</p>
<section id="county-and-race-tabyl" class="level3">
<h3 class="anchored" data-anchor-id="county-and-race-tabyl">County and race tabyl</h3>
<p>In this table we’ll look at arrest county and race to see if any counties have higher percentages of Black arrests in general (not just smuggling arrests).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>olsdata <span class="sc">|&gt;</span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tabyl</span>(arrest_county, person_race_abbr) <span class="sc">|&gt;</span> </span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_percentages</span>() <span class="sc">|&gt;</span> </span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_pct_formatting</span>() <span class="sc">|&gt;</span> </span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_ns</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> arrest_county         A           B             H        I         U
       Andrews 0.0%  (0) 12.4%  (23) 56.5%   (105) 0.0% (0) 0.0%  (0)
       Aransas 0.0%  (0)  4.0%  (14) 38.9%   (136) 0.0% (0) 0.0%  (0)
           Bee 0.0%  (0)  7.6%  (30) 68.6%   (271) 0.0% (0) 0.0%  (0)
        Borden 0.0%  (0) 20.0%   (1) 40.0%     (2) 0.0% (0) 0.0%  (0)
      Brewster 0.6%  (2) 12.3%  (43) 45.3%   (158) 0.0% (0) 0.0%  (0)
        Brooks 0.3%  (3)  6.3%  (62) 81.6%   (806) 0.0% (0) 0.2%  (2)
       Cameron 0.1%  (2)  1.4%  (46) 84.9% (2,756) 0.0% (0) 0.0%  (0)
          Coke 0.0%  (0) 31.0%  (13) 42.9%    (18) 0.0% (0) 0.0%  (0)
        Concho 1.8%  (1) 14.0%   (8) 33.3%    (19) 0.0% (0) 0.0%  (0)
         Crane 0.0%  (0) 23.5%   (4) 64.7%    (11) 0.0% (0) 0.0%  (0)
      Crockett 0.0%  (0) 19.8%  (68) 58.0%   (199) 0.0% (0) 0.0%  (0)
     Culberson 0.8%  (3) 19.6%  (72) 54.1%   (199) 0.3% (1) 0.8%  (3)
        Dawson 0.8%  (1) 14.6%  (19) 69.2%    (90) 0.0% (0) 0.0%  (0)
        Dimmit 0.0%  (0) 13.2% (116) 68.9%   (604) 0.0% (0) 0.0%  (0)
         Duval 0.0%  (0)  2.9%   (6) 76.2%   (157) 0.0% (0) 0.0%  (0)
         Ector 0.3%  (5) 10.0% (193) 59.6% (1,150) 0.1% (1) 0.0%  (0)
       Edwards 0.2%  (1) 18.4% (105) 63.5%   (362) 0.0% (0) 0.0%  (0)
       El Paso 0.0%  (1)  3.3% (131) 74.0% (2,942) 0.0% (0) 0.0%  (1)
        Gaines 0.0%  (0) 11.5%   (6) 53.8%    (28) 0.0% (0) 0.0%  (0)
     Glasscock 0.0%  (0) 25.0%   (1) 75.0%     (3) 0.0% (0) 0.0%  (0)
       Hidalgo 0.0%  (3)  0.9%  (57) 82.9% (5,334) 0.0% (0) 0.0%  (0)
        Howard 0.0%  (0) 23.1%  (42) 46.7%    (85) 0.0% (0) 0.0%  (0)
      Hudspeth 0.0%  (0) 19.1%  (70) 51.6%   (189) 0.0% (0) 0.0%  (0)
         Irion 0.0%  (0)  0.0%   (0) 40.0%     (2) 0.0% (0) 0.0%  (0)
    Jeff Davis 0.0%  (0) 21.3%  (19) 58.4%    (52) 0.0% (0) 0.0%  (0)
      Jim Hogg 0.0%  (0)  0.7%   (7) 79.2%   (805) 0.0% (0) 0.0%  (0)
     Jim Wells 0.2%  (1)  3.0%  (16) 82.7%   (444) 0.0% (0) 0.0%  (0)
        Kenedy 0.8%  (2) 11.0%  (28) 71.8%   (183) 0.0% (0) 0.0%  (0)
        Kimble 0.0%  (0) 24.2%  (62) 51.2%   (131) 0.0% (0) 0.0%  (0)
        Kinney 0.1%  (5)  9.2% (663) 82.8% (5,981) 0.0% (0) 0.0%  (2)
       Kleberg 0.4%  (3) 14.0%  (97) 73.4%   (510) 0.0% (0) 0.0%  (0)
      La Salle 0.3%  (2) 10.3%  (81) 75.9%   (596) 0.0% (0) 0.0%  (0)
      Live Oak 0.0%  (0) 10.7%  (41) 64.7%   (247) 0.0% (0) 0.0%  (0)
        Loving 0.0%  (0)  0.0%   (0) 25.0%     (1) 0.0% (0) 0.0%  (0)
        Martin 0.0%  (0) 34.5%  (19) 45.5%    (25) 0.0% (0) 0.0%  (0)
         Mason 0.0%  (0) 12.0%   (3) 44.0%    (11) 0.0% (0) 0.0%  (0)
      Maverick 0.2% (15)  2.9% (216) 91.7% (6,836) 0.0% (0) 0.8% (57)
     Mcculloch 0.0%  (0) 13.7%  (13) 24.2%    (23) 0.0% (0) 0.0%  (0)
     McCulloch 2.2%  (1) 22.2%  (10) 28.9%    (13) 0.0% (0) 0.0%  (0)
        Menard 0.0%  (0) 36.4%   (4) 36.4%     (4) 0.0% (0) 0.0%  (0)
       Midland 0.3%  (3) 18.4% (197) 53.6%   (572) 0.0% (0) 0.0%  (0)
        Nueces 0.5%  (5)  8.0%  (81) 60.1%   (608) 0.0% (0) 0.0%  (0)
         Pecos 0.2%  (2) 22.3% (250) 54.1%   (605) 0.0% (0) 0.0%  (0)
      Presidio 0.0%  (0)  2.0%   (2) 66.3%    (65) 0.0% (0) 0.0%  (0)
        Reagan 0.0%  (0)  8.3%   (2) 50.0%    (12) 0.0% (0) 0.0%  (0)
          Real 0.0%  (0)  5.5%   (3) 70.9%    (39) 0.0% (0) 0.0%  (0)
        Reeves 0.0%  (0) 18.8%  (70) 56.8%   (212) 0.0% (0) 0.0%  (0)
       Refugio 0.0%  (0) 20.3%  (52) 60.5%   (155) 0.0% (0) 0.0%  (0)
  San Patricio 1.1% (14)  8.4% (107) 61.6%   (789) 0.0% (0) 0.0%  (0)
    Schleicher 0.0%  (0) 26.7%   (4) 33.3%     (5) 0.0% (0) 0.0%  (0)
         Starr 0.1%  (2)  0.9%  (21) 86.3% (2,015) 0.0% (0) 0.0%  (0)
      Sterling 0.0%  (0) 14.3%   (7) 71.4%    (35) 0.0% (0) 0.0%  (0)
        Sutton 2.3%  (8) 21.0%  (73) 60.9%   (212) 0.0% (0) 0.0%  (0)
       Terrell 0.0%  (0) 20.1%  (30) 67.8%   (101) 0.0% (0) 0.0%  (0)
     Tom Green 0.8%  (9) 15.6% (181) 42.2%   (490) 0.0% (0) 0.0%  (0)
         Upton 0.0%  (0) 20.0%   (9) 48.9%    (22) 0.0% (0) 0.0%  (0)
        Uvalde 0.0%  (0)  9.2% (175) 71.7% (1,366) 0.0% (0) 0.0%  (0)
     Val Verde 0.0%  (0) 11.9% (219) 75.1% (1,382) 0.0% (0) 0.0%  (0)
          Ward 0.0%  (0) 16.7%  (34) 57.8%   (118) 0.0% (0) 0.0%  (0)
          Webb 0.1%  (3)  1.6%  (54) 86.2% (2,918) 0.0% (0) 0.0%  (0)
       Willacy 0.0%  (0) 10.8%  (41) 71.4%   (270) 0.0% (0) 0.0%  (0)
       Winkler 0.0%  (0) 18.1%  (13) 48.6%    (35) 0.0% (0) 1.4%  (1)
        Zapata 0.0%  (0)  0.8%   (2) 91.1%   (224) 0.0% (0) 0.0%  (0)
        Zavala 0.1%  (1) 12.5% (151) 71.3%   (864) 0.0% (0) 0.1%  (1)
           W         NA_
 31.2%  (58)  0.0%   (0)
 56.6% (198)  0.6%   (2)
 23.8%  (94)  0.0%   (0)
 40.0%   (2)  0.0%   (0)
 38.7% (135)  3.2%  (11)
 10.0%  (99)  1.6%  (16)
 11.9% (386)  1.7%  (56)
 26.2%  (11)  0.0%   (0)
 49.1%  (28)  1.8%   (1)
 11.8%   (2)  0.0%   (0)
 19.8%  (68)  2.3%   (8)
 24.5%  (90)  0.0%   (0)
 14.6%  (19)  0.8%   (1)
 16.3% (143)  1.5%  (13)
 20.4%  (42)  0.5%   (1)
 29.1% (562)  1.0%  (20)
 17.2%  (98)  0.7%   (4)
 18.2% (723)  4.4% (175)
 34.6%  (18)  0.0%   (0)
  0.0%   (0)  0.0%   (0)
 14.7% (947)  1.4%  (92)
 28.0%  (51)  2.2%   (4)
 26.8%  (98)  2.5%   (9)
 40.0%   (2) 20.0%   (1)
 20.2%  (18)  0.0%   (0)
 19.3% (196)  0.8%   (8)
 12.7%  (68)  1.5%   (8)
 15.7%  (40)  0.8%   (2)
 23.0%  (59)  1.6%   (4)
  7.3% (527)  0.7%  (48)
 11.7%  (81)  0.6%   (4)
 11.5%  (90)  2.0%  (16)
 23.3%  (89)  1.3%   (5)
 75.0%   (3)  0.0%   (0)
 20.0%  (11)  0.0%   (0)
 44.0%  (11)  0.0%   (0)
  3.8% (287)  0.6%  (47)
 61.1%  (58)  1.1%   (1)
 46.7%  (21)  0.0%   (0)
 27.3%   (3)  0.0%   (0)
 26.3% (281)  1.4%  (15)
 27.6% (279)  3.8%  (38)
 22.3% (250)  1.1%  (12)
 28.6%  (28)  3.1%   (3)
 29.2%   (7) 12.5%   (3)
 23.6%  (13)  0.0%   (0)
 21.2%  (79)  3.2%  (12)
 16.8%  (43)  2.3%   (6)
 28.4% (364)  0.5%   (7)
 40.0%   (6)  0.0%   (0)
 11.5% (268)  1.2%  (29)
 14.3%   (7)  0.0%   (0)
 15.2%  (53)  0.6%   (2)
 12.1%  (18)  0.0%   (0)
 40.5% (470)  0.9%  (11)
 31.1%  (14)  0.0%   (0)
 17.6% (336)  1.4%  (27)
 12.1% (223)  0.8%  (15)
 24.0%  (49)  1.5%   (3)
  9.1% (307)  3.1% (104)
 17.2%  (65)  0.5%   (2)
 31.9%  (23)  0.0%   (0)
  8.1%  (20)  0.0%   (0)
 15.1% (183)  0.9%  (11)</code></pre>
</div>
</div>
<p>Since none of the percentages of Black arrests are greater than 25% and there are only 7 categories, it doesn’t seem like there is any one county that is arresting more Black people than other races at a significant rate.</p>
</section>
<section id="smuggling-arrests-by-race-and-county" class="level3">
<h3 class="anchored" data-anchor-id="smuggling-arrests-by-race-and-county">Smuggling arrests by race and county %</h3>
<p>We’ll now look specifically into the percentages of smuggling arrests to see if any county is arresting Black people for smuggling more than other races.</p>
<p>*** NOTE TO SELF: THIS DOESN’T WORK. It should add up to 100% down each column but it doesn’t. ***</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>cat_ols <span class="sc">|&gt;</span> </span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(charge_cat <span class="sc">==</span> <span class="st">"Smuggling/Trafficking of Persons"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tabyl</span>(person_race_abbr, arrest_county) <span class="sc">|&gt;</span> </span>
<span id="cb91-4"><a href="#cb91-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_percentages</span>() <span class="sc">|&gt;</span> </span>
<span id="cb91-5"><a href="#cb91-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_pct_formatting</span>() <span class="sc">|&gt;</span> </span>
<span id="cb91-6"><a href="#cb91-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 52
  person_race_abbr Aransas Bee   Brewster Brooks Cameron Crockett Culberson
  &lt;chr&gt;            &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt;  &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;    
1 A                0.0%    0.0%  0.0%     0.0%   0.0%    0.0%     0.0%     
2 B                0.1%    0.1%  0.2%     1.4%   0.2%    0.8%     0.3%     
3 H                0.0%    0.2%  0.5%     2.9%   1.7%    0.6%     0.5%     
4 U                0.0%    0.0%  0.0%     0.0%   0.0%    0.0%     0.0%     
5 W                0.2%    0.3%  0.3%     1.6%   1.0%    0.6%     0.3%     
6 &lt;NA&gt;             0.0%    0.0%  0.0%     4.0%   1.7%    0.6%     0.0%     
# ℹ 44 more variables: Dawson &lt;chr&gt;, Dimmit &lt;chr&gt;, Duval &lt;chr&gt;, Ector &lt;chr&gt;,
#   Edwards &lt;chr&gt;, `El Paso` &lt;chr&gt;, Gaines &lt;chr&gt;, Hidalgo &lt;chr&gt;, Howard &lt;chr&gt;,
#   Hudspeth &lt;chr&gt;, `Jeff Davis` &lt;chr&gt;, `Jim Hogg` &lt;chr&gt;, `Jim Wells` &lt;chr&gt;,
#   Kenedy &lt;chr&gt;, Kimble &lt;chr&gt;, Kinney &lt;chr&gt;, Kleberg &lt;chr&gt;, `La Salle` &lt;chr&gt;,
#   `Live Oak` &lt;chr&gt;, Martin &lt;chr&gt;, Maverick &lt;chr&gt;, Menard &lt;chr&gt;,
#   Midland &lt;chr&gt;, Nueces &lt;chr&gt;, Pecos &lt;chr&gt;, Presidio &lt;chr&gt;, Reagan &lt;chr&gt;,
#   Real &lt;chr&gt;, Reeves &lt;chr&gt;, Refugio &lt;chr&gt;, `San Patricio` &lt;chr&gt;, …</code></pre>
</div>
</div>
</section>
<section id="looking-into-specific-officers" class="level3">
<h3 class="anchored" data-anchor-id="looking-into-specific-officers">Looking into specific officers</h3>
<p>Let’s see if any officers stick out as arresting more Black people than other races. We’ll filter their arrests to be more than 100 so we can ensure that there are a large # of arrests by a specific officer in general. (Otherwise findings wouldn’t be very significant.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>olsdata <span class="sc">|&gt;</span> </span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tabyl</span>(arresting_officer, person_race_abbr) <span class="sc">|&gt;</span></span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_totals</span>(<span class="st">"col"</span>, <span class="at">name =</span> <span class="st">"col_total"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_totals</span>(<span class="st">"row"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>() <span class="sc">|&gt;</span> </span>
<span id="cb93-6"><a href="#cb93-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(col_total)) <span class="sc">|&gt;</span> </span>
<span id="cb93-7"><a href="#cb93-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(col_total <span class="sc">&gt;</span> <span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 63 × 9
   arresting_officer     A     B     H     I     U     W   NA_ col_total
   &lt;chr&gt;             &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;
 1 Total                98  4187 44602     2    67  8822   857     58635
 2 &lt;NA&gt;                 98  1034 14302     2    67  1753     0     17256
 3 Derrick Hinojosa      0     2   296     0     0    42     0       340
 4 Jose Mendoza          0     2   269     0     0    45     6       322
 5 David Poland          0    32    79     0     0   143    34       288
 6 Juan Sauceda          0     3   210     0     0    26     3       242
 7 Jose Delafuente       0     1   217     0     0    17     6       241
 8 Arnold Rodriguez      0     0   197     0     0    11     7       215
 9 Sarah Oranday         0    28   159     0     0    25     0       212
10 Alejandro Morante     0    28   117     0     0    51     1       197
# ℹ 53 more rows</code></pre>
</div>
</div>
<p>This also doesn’t look super indicative of anything.</p>
</section>
</section>
<section id="main-takeaways" class="level2">
<h2 class="anchored" data-anchor-id="main-takeaways">Main takeaways</h2>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>